apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: randomitems.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: k8s.io
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: 
              - item
              properties:
                item: 
                  type: string
                  enum:
                  - fact
                  - joke
                  - quote
            status:
              type: object
              properties:
                item:
                  type: string
                value:
                  type: string
      subresources:
        status: {}
  names:
    kind: RandomItem
    plural: randomitems
  scope: Namespaced
